"""Tambah fitur konfirmasi pembayaran

Revision ID: 6988c2e771fe
Revises: da24f9174990
Create Date: 2025-11-02 19:50:14.615441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6988c2e771fe'
down_revision = 'da24f9174990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('penyewa', 'admin', 'staff'),
               type_=sa.Enum('penyewa', 'staff', 'admin'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('penyewa', 'staff', 'admin'),
               type_=mysql.ENUM('penyewa', 'admin', 'staff'),
               existing_nullable=False)

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('payment_proof')

    # ### end Alembic commands ###
